services:
  - type: web
    name: venturereel
    env: php
    region: singapore
    plan: free
    buildCommand: >
      composer install --no-dev --optimize-autoloader &&
      npm ci &&
      npm run build &&
      php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: VentureReel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://venturereel.onrender.com
      - key: APP_KEY
        value: base64:Tgq+QBke7wGqdsrzHRUimiw/tNuSDP8YmKzSBJqWV6s=
      - key: DB_CONNECTION
        value: mysql
      - key: CACHE_DRIVER
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: VentureReel
